Hw05 avatars
OspanovaV/nodejs-rest-api pull request #4
Opened 2023-01-17 20:41 UTC by OspanovaV

2023-01-18 15:09 UTC, BohdanGres commented on controllers/auth/updateAvatar.js
> +const updateAvatar = async(req, res) => {
забули привести аватар до потрібних розморів за допомогою https://www.npmjs.com/package/jimp

2023-01-18 15:10 UTC, BohdanGres requested changes
все добре, треба трошки доробити

2023-01-18 21:18 UTC, OspanovaV commented on controllers/auth/updateAvatar.js
> +const updateAvatar = async(req, res) => {
дякую. Виправила

2023-01-19 13:16 UTC, BohdanGres commented on controllers/auth/updateAvatar.js
> +    resizeAvatar.resize(250, 250).writeAsync(resultUpload);
тут await має бути інакше помилку не зловить потенційну

2023-01-19 13:17 UTC, BohdanGres approved these changes
все добре

2023-01-20 09:06 UTC, merged